Numpy

1.	Criar um array NumPy de uma dimensão com 10 zeros.
2.	Modificar o array anterior, alterando o quinto valor para 1.
3.	Criar um array NumPy com valores de 10 a 49.
4.	Inverter a ordem dos elementos no array criado na questão 3.
5.	Encontrar os índices dos elementos não-nulos de [3, 0, 4, 0, 5, 7].


In [9]:
#1
import numpy as np 
rng = np.random.default_rng(seed=42)
dados_amostra = rng.integers(low=1, high=10, size= 10)
display(dados_amostra)
# 2
dados_amostra[4]=1
display(dados_amostra)
# 3
rng2 = np.random.default_rng(seed=42)
dados_amostra2 = rng2.integers(low=10, high=49, size= 10)
display(dados_amostra2)

# 4 

dados_amostra3= np.flip(dados_amostra2) #INVERTER A LISTA
dados_amostra3

# 5
Lista_ati= np.array([3, 0, 4, 0, 5, 7])
print(Lista_ati)
nao_nulos = np.nonzero(Lista_ati)#devolve o index dos numero diferente de zero
nao_nulos


array([1, 7, 6, 4, 4, 8, 1, 7, 2, 1], dtype=int64)

array([1, 7, 6, 4, 1, 8, 1, 7, 2, 1], dtype=int64)

array([13, 40, 35, 27, 26, 43, 13, 37, 17, 13], dtype=int64)

[3 0 4 0 5 7]


(array([0, 2, 4, 5], dtype=int64),)

In [2]:
import numpy as np

rng = np.random.default_rng(seed=42)
dados_vendas = rng.integers(low=1 ,high=10,size=10)
display(dados_vendas)
numero_maior = np.argmax(dados_vendas) #pega o index do maior numero do array

display(dados_vendas[5])
numero_maior

array([1, 7, 6, 4, 4, 8, 1, 7, 2, 1], dtype=int64)

8

5

6.	Criar uma matriz 3x3 com valores de 0 a 8.
7.	Encontrar os valores mínimo e máximo de um array criado com números aleatórios de tamanho 10.

In [3]:
# 6
rng = np.random.default_rng(seed=42)
numero_lista = rng.integers(low=0, high=8 , size=9 )

lista_3_3_1 = numero_lista.reshape(3,3) #tem essa forma de fazer 
display(lista_3_3_1)
lista_3_3 = np.reshape(numero_lista, (3,3)) # e tem essa forma tb
display(lista_3_3)

# 7

numero_lista_2 = rng.integers(low=0, high=50 , size=10 )


maior_numero_lista = np.argmax(numero_lista_2) #devolve o index
print(maior_numero_lista)
print(numero_lista_2)




array([[0, 6, 5],
       [3, 3, 6],
       [0, 5, 1]], dtype=int64)

array([[0, 6, 5],
       [3, 3, 6],
       [0, 5, 1]], dtype=int64)

2
[ 4 26 48 36 38 35 39 25  6 41]


8.	Normalizar um array de 5x5 aleatório para que os valores variem de 0 a 1. (Normalizar significa subtrair o mínimo e dividir pela diferença entre o máximo e o mínimo).
9.	Multiplicar uma matriz 5x3 por uma matriz 3x2.
10.	Subtrair a média de cada linha de uma matriz.

In [8]:
# 8

import numpy as np

# Criar um array aleatório de 5x5
array_aleatorio = np.random.rand(5, 5)

# Encontrar o valor mínimo e máximo do array
valor_minimo = array_aleatorio.min()
valor_maximo = array_aleatorio.max()

# Normalizar o array
array_normalizado = (array_aleatorio - valor_minimo) / (valor_maximo - valor_minimo)

print("Array original:")
print(array_aleatorio)
print("\nArray normalizado:")
print(array_normalizado)


Array original:
[[0.25623446 0.20607564 0.9151056  0.06831485 0.03949145]
 [0.17046481 0.55306982 0.97325881 0.712017   0.0264795 ]
 [0.05322267 0.4694858  0.07226124 0.62977165 0.71342178]
 [0.30241687 0.85857449 0.52821847 0.81126272 0.18529585]
 [0.27996087 0.51635138 0.52953007 0.37607603 0.44007347]]

Array normalizado:
[[0.24267003 0.18969166 0.93857786 0.04418702 0.01374339]
 [0.15207906 0.5561912  1.         0.72407317 0.        ]
 [0.02824646 0.46790872 0.04835523 0.63720462 0.72555692]
 [0.29144846 0.878869   0.52994289 0.82889773 0.16774379]
 [0.26773015 0.51740873 0.53132822 0.36924817 0.43684306]]


In [5]:
array_aleatorio1 = np.random.rand(5, 3)
array_aleatorio2 = np.random.rand(3, 2)

multiplca = np.dot(array_aleatorio1,array_aleatorio2)# multiplcaçoa de matrizes
multiplca

array([[0.8320081 , 0.63905166],
       [0.66236713, 0.49425132],
       [1.19063793, 0.90757751],
       [0.69150692, 0.51767333],
       [0.67008846, 0.55905636]])

In [6]:
import numpy as np

rng = np.random.default_rng(seed=42)
numero_lista = rng.integers(low=0, high=70 , size=9 )
numero_lista




array([ 6, 54, 45, 30, 30, 60,  6, 48, 14], dtype=int64)